export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SORT = "SET_SORT";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_TOTAL_ITEMS = "SET_TOTAL_ITEMS";
